import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { FillUpGuardrailList } from "@/components/planning/fill-up/FillUpGuardrailList";
import type { FillUpPlanningClusterResult } from "@/domain/services/fillUpPlanningService";
import { Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

export function FillUpClusterDetails({ result }: { result: FillUpPlanningClusterResult | null }) {
  if (!result) return <Card className="border-dashed"><CardContent className="py-6 text-sm text-muted-foreground">Wähle einen Cluster in der Tabelle, um seine Kapazitätsbasis, Limiter und Szenarien zu prüfen.</CardContent></Card>;
  const mix = result.recommendation.workloadMixRecommendation;
  const baseline = result.capacity.normal;
  const chartData = result.hours.map((hour) => ({
    timestamp: new Date(hour.timestampUtc).toLocaleDateString("de-DE", { day: "2-digit", month: "2-digit", hour: "2-digit" }),
    cpuDemandMHz: hour.clusterCpuDemandMHz,
    memoryUtilizationGiB: hour.clusterMemoryUtilizationMiB === null ? null : hour.clusterMemoryUtilizationMiB / 1024,
  }));
  return <Card className="border-l-4 border-l-primary"><CardHeader className="border-b bg-muted/20"><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle>{result.cluster.name}</CardTitle><CardDescription>{result.policy.name} v{result.policy.version} · ungünstigster Normal-Slot {baseline.worstTimestampUtc ? new Date(baseline.worstTimestampUtc).toLocaleString("de-DE") : "—"}</CardDescription></div><Badge variant={baseline.status === "red" ? "destructive" : baseline.status === "green" ? "default" : "secondary"}>Baseline: {baseline.status}</Badge></div></CardHeader><CardContent className="space-y-5 pt-5"><div className="grid gap-5 lg:grid-cols-[18rem_minmax(0,1fr)]"><div className="grid grid-cols-2 gap-2 lg:grid-cols-1"><Fact label="Gemeinsamer Mix" value={mix?.maxAdditionalVms === null || mix?.maxAdditionalVms === undefined ? "—" : `+${mix.maxAdditionalVms} VMs`} /><Fact label="N-1-Verlust" value={mix?.relativeN1LossPct === null || mix?.relativeN1LossPct === undefined ? "—" : `${mix.relativeN1LossPct.toLocaleString("de-DE", { maximumFractionDigits: 1 })} %`} /><Fact label="CPU Demand" value={baseline.cpuDemandMHz === null ? "—" : `${baseline.cpuDemandMHz.toLocaleString("de-DE", { maximumFractionDigits: 0 })} MHz`} /><Fact label="RAM zugewiesen" value={baseline.assignedMemoryMiB === null ? "—" : `${Math.round(baseline.assignedMemoryMiB / 1024).toLocaleString("de-DE")} GiB`} /></div><div className="space-y-2"><h3 className="text-sm font-semibold">Aktive Guardrails</h3><FillUpGuardrailList guardrails={result.recommendation.guardrails.filter((entry) => entry.hardLimit)} /></div></div><section className="rounded-md border bg-muted/10 p-3"><div className="mb-2"><h3 className="text-sm font-semibold">Historischer Verlauf</h3><p className="text-xs text-muted-foreground">Direkte Clusterzeitreihen aus dem ausgewählten Import; die gleiche Datenbasis steuert den ungünstigsten Szenario-Slot.</p></div><div className="h-56"><ResponsiveContainer width="100%" height="100%"><LineChart data={chartData} margin={{ top: 6, right: 8, left: 4, bottom: 0 }}><XAxis dataKey="timestamp" minTickGap={44} tick={{ fontSize: 10 }} /><YAxis yAxisId="cpu" tick={{ fontSize: 10 }} width={46} /><YAxis yAxisId="memory" orientation="right" tick={{ fontSize: 10 }} width={42} /><Tooltip formatter={(value: number, name: string) => [value.toLocaleString("de-DE", { maximumFractionDigits: 0 }), name]} /><Legend wrapperStyle={{ fontSize: 12 }} /><Line yAxisId="cpu" dataKey="cpuDemandMHz" name="CPU Demand MHz" type="monotone" stroke="hsl(var(--primary))" dot={false} strokeWidth={2} connectNulls /><Line yAxisId="memory" dataKey="memoryUtilizationGiB" name="Memory Util. GiB" type="monotone" stroke="hsl(var(--chart-2))" dot={false} strokeWidth={2} connectNulls /></LineChart></ResponsiveContainer></div></section></CardContent></Card>;
}

function Fact({ label, value }: { label: string; value: string }) { return <div className="rounded-md border bg-muted/20 px-3 py-2"><p className="text-xs text-muted-foreground">{label}</p><p className="font-mono text-sm font-semibold tabular-nums">{value}</p></div>; }
