import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { InfoTooltip } from "@/components/ui/info-tooltip";
import { useFillUpAnalysisRuns } from "@/hooks/useFillUpAnalysisRuns";
import { buildFillUpRunMarkdown, createFillUpAnalysisRun, duplicateFillUpAnalysisRun, renameFillUpAnalysisRun } from "@/domain/services/fillUpRunService";
import type { FillUpPlanningClusterResult } from "@/domain/services/fillUpPlanningService";
import type { FillUpWorkloadMix, FillUpWorkloadProfile, VropsTimeSeriesImport } from "@/domain/models/types";
import { Copy, Files, Pencil, Plus, Trash2 } from "lucide-react";
import { FILL_UP_UI } from "@/lib/glossaries/planning";
import { toast } from "sonner";

export function FillUpRunHistory({ importMeta, results, profiles, workloadMix, includeN2, cpuDemandConcurrencyPct }: { importMeta: VropsTimeSeriesImport | null; results: readonly FillUpPlanningClusterResult[]; profiles: readonly FillUpWorkloadProfile[]; workloadMix: FillUpWorkloadMix | null; includeN2: boolean; cpuDemandConcurrencyPct: number }) {
  const { runs, save, remove, isSaving } = useFillUpAnalysisRuns();
  const saveCurrent = async () => { if (!importMeta || !results.length) return; await save(createFillUpAnalysisRun({ name: `Fill Up ${new Date().toLocaleString("de-DE")}`, importMeta, results, profiles, workloadMix, includeN2, cpuDemandConcurrencyPct })); toast.success("Analyzer-Run lokal gespeichert."); };
  const rename = async (id: string) => { const run = runs.find((entry) => entry.id === id); const name = run && window.prompt("Run-Name", run.name); if (run && name) await save(renameFillUpAnalysisRun(run, name)); };
  const copy = async (id: string) => { const run = runs.find((entry) => entry.id === id); if (run) { await navigator.clipboard.writeText(buildFillUpRunMarkdown(run)); toast.success("Run als Markdown kopiert."); } };
  return <Card><CardHeader className="flex-row items-center justify-between space-y-0"><InfoTooltip entry={FILL_UP_UI.runHistory} side="right"><CardTitle className="w-fit cursor-help text-base">Gespeicherte Analyzer-Runs</CardTitle></InfoTooltip><Button size="sm" onClick={() => void saveCurrent()} disabled={!importMeta || !results.length || isSaving}><Plus className="mr-1.5 h-4 w-4" />Run speichern</Button></CardHeader><CardContent className="space-y-2">{runs.length === 0 ? <p className="text-sm text-muted-foreground">Noch kein Run gespeichert. Ein Run hält Import-, Policy-, Profil- und Ergebnis-Snapshot unveränderlich fest.</p> : runs.map((run) => <div key={run.id} className="flex flex-wrap items-center justify-between gap-2 rounded-md border bg-muted/15 px-3 py-2"><div><p className="text-sm font-medium">{run.name}</p><p className="text-xs text-muted-foreground">{new Date(run.createdAt).toLocaleString("de-DE")} · {run.results.length} Cluster · Import {run.importId.slice(0, 8)}</p></div><div className="flex gap-1"><Button variant="ghost" size="icon" aria-label="Run umbenennen" onClick={() => void rename(run.id)}><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="icon" aria-label="Run duplizieren" onClick={() => void save(duplicateFillUpAnalysisRun(run))}><Files className="h-4 w-4" /></Button><Button variant="ghost" size="icon" aria-label="Run als Markdown kopieren" onClick={() => void copy(run.id)}><Copy className="h-4 w-4" /></Button><Button variant="ghost" size="icon" aria-label="Run löschen" onClick={() => void remove(run.id)}><Trash2 className="h-4 w-4 text-destructive" /></Button></div></div>)}</CardContent></Card>;
}
